* Publish first iteration
** Fix crashes
*** Symptom
    occurred after fresh create, after hitting "edit"
*** stacktrace
01-02 08:14:04.950  20055-20055/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.tknilsson.habitboss, PID: 20055
    java.lang.NullPointerException
            at com.tknilsson.habitboss.ui.HabitPageFragment.initUI(HabitPageFragment.java:79)
            at com.tknilsson.habitboss.ui.MainActivity.refreshAllHabitPages(MainActivity.java:199)
            at com.tknilsson.habitboss.ui.BackgroundWorker.work(BackgroundWorker.java:39)
            at com.tknilsson.habitboss.ui.BackgroundWorker.access$000(BackgroundWorker.java:11)
            at com.tknilsson.habitboss.ui.BackgroundWorker$1.run(BackgroundWorker.java:30)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

** Notifications
   http://developer.android.com/guide/topics/ui/notifiers/notifications.html#Managing

   Have NotificationsManager run on every start/resume/stop:

   Create new daily n only if not created yet & dailies still remain - run one hour before midnight
   Create new weekly only if not created yet & weeklies still remain - run mid-sunday
   Create new monthly only if not created yet & monthlies still remain - run the 27th of the month

   IF no dailies, remove any exisiting daily notification
   IF no weeklies, remove any exisiting daily notification
   IF no monthlies, remove any exisiting daily notification

   All notificaitons: have descriptive text for time window type
   Aslo include link/intent to start app to check/update habits

** Improve look-n-feel
*** Style/theme app with striking colors
    Pick out color theme
    Use color scheme picker
    Play with style generator
    Orange & teal
    Orange most dominant, less subtle, used for alerts, notifications, removal
    Blue more suble, multiple shades, most muted, used for confirmations, toasts, dialogs, most widgets
*** Proper launcher/up icon
    Blue flat background matching the scheme
    orange stylized wakeup clock with checkmark instead of hands
    Bells and legs
    very slight gradient and 1px highlight/shadow both on launcher icon edges and the clock object(s)
*** replace some buttons/texts with iconography & colors
    Make Done a (colored) checkmark icon, never put it in overflow
    Make Remove buttons simple (colored) x icons
    Make Done! button striking orange
    Make Undo button a back/return icon
** Publish v1 on marketplace
   Make it require at least v4.0
   Clean up code
   Make it available
   Also spend some time on marketplace to about visibility etc
   http://developer.android.com/distribute/index.html


* More features
** Make existing habits texts editable in edit mode
** Add drag-n-drop reordering when editing habits
   https://github.com/bauerca/drag-sort-listview
** Backend sync
   Use Cloud Save or Google Drive SDK, or something else?
** Visualize streaks
   Streaks action in menu, go to separate actity
   On tablet, just show in-activity?
   Implement and persist Habit.fails variable
   Seinfeld calendar view: visualize each habit streak
** Support Nexus 7/tablet form factors
   Add custom layout?
   Make text of each habit clickable, act as detail view trigger
   In remaining screen real-estate: show Seinfeld cal & stats for each habit?
** Add animations
** More satisfying/visceral feedback on clearing habits
   Add pleasant/gratifiying feedback when all dailies/weeklies/monthlies have been cleared.
   Vibration
   Streamers, confetti
   Funny "you are awesome!" popup text
   Stylized unicorn, puppies, kittens, etc gfx?
   Fanfare if sound is turned on
   This is a touch of gamification. Think popcap/blizzard - Peggle!
