* Publish first iteration
** Notifications
   http://developer.android.com/guide/topics/ui/notifiers/notifications.html#Managing

   Have NotificationsManager run on every start/resume/stop:

   Create new daily n only if not created yet & dailies still remain - run one hour before midnight
   Create new weekly only if not created yet & weeklies still remain - run mid-sunday
   Create new monthly only if not created yet & monthlies still remain - run the 27th of the month

   IF no dailies, remove any exisiting daily notification
   IF no weeklies, remove any exisiting daily notification
   IF no monthlies, remove any exisiting daily notification

   All notificaitons: have descriptive text for time window type
   Aslo include link/intent to start app to check/update habits

** Finish Habit(s) testcase
   Add due date/remaining tests
   Cleanup testcase in general

** Improve look-n-feel
*** Style/theme app with striking colors
    Pick out color theme
    Use color scheme picker
    Play with style generator
    Orange & teal
    Orange most dominant, less subtle, used for alerts, notifications, removal
    Blue more suble, multiple shades, most muted, used for confirmations, toasts, dialogs, most widgets
*** Proper launcher/up icon
    Blue flat background matching the scheme
    orange stylized wakeup clock with checkmark instead of hands
    Bells and legs
    very slight gradient and 1px highlight/shadow both on launcher icon edges and the clock object(s)
*** replace some buttons/texts with iconography & colors
    Make Done a (colored) checkmark icon, never put it in overflow
    Make Remove buttons simple (colored) x icons
    Make Done! button striking orange
    Make Undo button a back/return icon
** Support 2.3.3
   Test in emulator
   Add compat lib for actionbar etc
** Publish v1 on marketplace
   Clean up code
   Make it available
   Check what happens with habits local file storage when upgrading version of app on play store
   Also spend some time on marketplace to about visibility etc
   http://developer.android.com/distribute/index.html
* More features
** Add drag-n-drop reordering when editing habits
   https://github.com/bauerca/drag-sort-listview
** Backend sync
   Use Cloud Save or Google Drive SDK, or something else?

** More satisfying/visceral feedback on clearing habits
   Add pleasant/gratifiying feedback when all dailies/weeklies/monthlies have been cleared.
   Vibration
   Streamers, confetti
   Funny "you are awesome!" popup text
   Stylized unicorn, puppies, kittens, etc gfx?
   Fanfare if sound is turned on
   This is a touch of gamification. Think popcap/blizzard - Peggle!
** Visualize streaks
   Streaks action in menu, go to separate actity
   On tablet, just show in-activity?
   Implement and persist Habit.fails variable
   Seinfeld calendar view: visualize each habit streak
** Support Nexus 7/tablet form factors
   Add custom layout?
   Make text of each habit clickable, act as detail view trigger
   In remaining screen real-estate: show Seinfeld cal & stats for each habit?
* Dev environment
** Go through vogella and google testing material again
** Add some roboelectric tests
** Add some robotium tests + test extensively on appthwack
** Tweak basic Junit testruns to run quicker
** Rewrite unit tests to use groovy
   Spock?
