* Publish first iteration
** Finish Habit(s) testcase
   Add due date/remaining tests
   Cleanup testcase in general
** Improve look-n-feel, UX
*** Add Undo button in edit mode, left of remove btn
*** Style/theme with striking colors
    Pick out color theme
    Use color scheme picker
    Play with style generator
    Orange & teal
    Orange most dominant, less subtle, used for alerts, notifications, removal
    Blue more suble, multiple shades, most muted, used for confirmations, toasts, dialogs, most widgets
*** Proper logo
    HabitBoss, habit in blue, boss in orange.
    Just add it in the readme for now.
    Inkscape/SVG it, put asset in git repo
*** Proper launcher/up icon
    Icon= Inkscape svg work: blue flat background, orange stylized wakeup clock with checkmark instead of hands
    Just put the svg in the git repo
*** edit mode actions
    Make edit and done separate actions
    Hide/show as needed
    Edit is still text, and put it in the overflow
*** replace some buttons/texts with iconography & colors
    Make Done a (colored) checkmark icon, never put it in overflow
    Make Remove buttons simple (colored) x icons
    Make Done! button striking orange
    Make Undo button a back/return icon
** Publish v1 on marketplace
   Make it available
   Check what happens with habits local file storage when upgrading version of app on play store
   Also spend some time on marketplace to about visibility etc
   http://developer.android.com/distribute/index.html
* More features
** Add drag-n-drop reordering when editing habits
   https://github.com/bauerca/drag-sort-listview
** Add external android notifications
   http://developer.android.com/guide/topics/ui/notifiers/notifications.html#Managing

   Create notifications when adding new habits, ticking exisitng ones
   Update notifications when ticking habits
   Remove notifications when removing habits, resetting habits, and deleting app
   Popup notifications on due soon/overdue items
   Pop up notifications when approaching/breaking deadlines
** Backend sync
   Use Cloud Save or Google Drive SDK, or something else?

** More satisfying/visceral feedback on clearing habits
   Add pleasant/gratifiying feedback when all dailies/weeklies/monthlies have been cleared.
   Vibration
   Streamers, confetti
   Funny "you are awesome!" popup text
   Stylized unicorn, puppies, kittens, etc gfx?
   Fanfare if sound is turned on
   This is a touch of gamification. Think popcap/blizzard - Peggle!
** Visualize streaks
   Streaks action in menu, go to separate actity
   On tablet, just show in-activity?
   Implement and persist Habit.fails variable
   Seinfeld calendar view: visualize each habit streak
** Support Nexus 7/tablet form factors
   Add custom layout?
   Make text of each habit clickable, act as detail view trigger
   In remaining screen real-estate: show Seinfeld cal & stats for each habit?
* Dev environment
** Go through vogella and google testing material again
** Add some roboelectric tests
** Add some robotium tests + test on appthwack
** Tweak basic Junit testruns to run quicker
** Rewrite unit tests to use groovy
   Spock?
