* First iteration
** Fix actionables number in tabs
*** Make refresh fire after habits are loaded, and each time actionable counts change
** Set up background processing
   Clear out habit checked data as each d/w/m ends
   Set much tighter time windows for each category to test: 1 sec, 10 sec, 1minute
** Implement the habit-breaking part
    have to answer "did you avoid... yesterday|last week|last month?"
    after each period?
    Store creation time, on each startup, check if any have surpassed
    their current day/week/month since last check, Fire off question to
    user if habit has been upheld.
** Add db persistence
   Create DAOs (use the greendao stuff)
   Swap out that arraylist with proper db-backed cursor or similar
   Initial dataset, include example habits
** Improve look and feel
   Fix Krita install!
*** Proper logo
    HabitBoss, habit in blue, boss in orange. Just add it in the readme for now.
    Inkscape/SVG it, put asset in git repo
*** Proper launcher icon
    Icon= Inkscape svg work: blue flat background, orange stylized wakeup clock with checkmark instead of hands
    Just put the svg in the git repo
*** Use icons instead of texts for action bar edit toggle
*** Style/theme with striking colors
    Orange & teal
    Orange most dominant, less subtle, used for alerts, notifications, removal
    Blue more suble, multiple shades, most muted, used for confirmations, toasts, dialogs, most widgets
    Use Pantone color book to find nice variations of blue and orange
    To find colors for each element in theme: blueshift regular holo themes & adjust from there
*** Figure out how to make entire screen scrollable when habits fill more than screen
** Add out-of app notifications
   Run in background
   Pop up notifications when approaching/breaking deadlines
   Pop up notifications with "did you avoid BADHABIT last period?"
   Link notifications into intent to HB app
** Publish on marketplace
   Make it available
   Also spend some time on marketplace, learn about visibility etc http://developer.android.com/distribute/index.html)
* More features
** More satisfying/visceral feedback on clearing habits
   Add pleasant/gratifiying feedback when all dailies/weeklies/monthlies have been cleared.
   Vibration
   Streamers, confetti
   Funny "you are awesome!" popup text
   Stylized unicorn, puppies, kittens, etc gfx?
   Fanfare if sound is turned on
   This is a touch of gamification. Think popcap/blizzard - Peggle!

** Store/visualize streaks/stats
   Implement and persist Habit.fails variable
   Seinfeld calendar view: visualize each habit streak
** Make habit descriptions editable in edit mode
   Show both editable and non editable field, show/hide as usual
** Backend sync
   Use Cloud Save or Google Drive SDK, or something else?
** Widget (resizable??)
** Special use case on first run: guided "wizard"/overlays for adding habit to make and break
** Support Nexus 7/tablet form factors
   Add custom layout?
   Make text of each habit clickable, act as detail view trigger
   In remaining screen real-estate: show Seinfeld cal & stats for each habit?
** Add drag-n-drop reordering of each habit list
   https://github.com/bauerca/drag-sort-listview
* Dev environment
** Go through vogella and google testing material again
** Add some roboelectric tests
** Add some robotium tests + test on appthwack
** Tweak basic Junit testruns to run quicker
** Rewrite unit tests to use groovy
   Spock?
