* First iteration
** Fix dueSoon/overdue/canbeMarked:

   fix time till due calculations work

   cleanup testcase

   update the fixtures to match all situations

   On adding new habit, display toast:
   "Remember: you have till midnight|sunday|the 31st to mark it as done for the first time."

   test test test

** Manage notifications
   http://developer.android.com/guide/topics/ui/notifiers/notifications.html#Managing

   Create notifications when adding new habits, ticking exisitng ones
   Update notifications when ticking habits
   Remove notifications when removing habits, resetting habits, and deleting app
   Popup notifications on due soon/overdue items
   Pop up notifications when approaching/breaking deadlines
** Improve look and feel
*** Pick out color theme
    Use color scheme picker
    Play with style generator
*** Style/theme with striking colors
    Extract indicator colors for habits into color theme as well
    Orange & teal
    Orange most dominant, less subtle, used for alerts, notifications, removal
    Blue more suble, multiple shades, most muted, used for confirmations, toasts, dialogs, most widgets
    Use Pantone color book to find nice variations of blue and orange
    To find colors for each element in theme: blueshift regular holo themes & adjust from there
*** Proper logo
    HabitBoss, habit in blue, boss in orange. Just add it in the readme for now.
    Inkscape/SVG it, put asset in git repo
*** Proper launcher icon && up-button
    Icon= Inkscape svg work: blue flat background, orange stylized wakeup clock with checkmark instead of hands
    Just put the svg in the git repo
*** Use icons instead of texts for action bar edit toggle?
** Publish v1 on marketplace
   Make it available
   Check what happens with habits local file storage when upgrading version of app on play store
   Also spend some time on marketplace, learn about visibility etc http://developer.android.com/distribute/index.html)
* More features
** Implement the habit-breaking part
    have to answer "did you avoid... yesterday|last week|last month?"
    after each period?
    Store creation time, on each startup, check if any have surpassed
    their current day/week/month since last check, Fire off question to
    user if habit has been upheld.
    Pop up notifications with "did you avoid BADHABIT last period?"
** More satisfying/visceral feedback on clearing habits
   Add pleasant/gratifiying feedback when all dailies/weeklies/monthlies have been cleared.
   Vibration
   Streamers, confetti
   Funny "you are awesome!" popup text
   Stylized unicorn, puppies, kittens, etc gfx?
   Fanfare if sound is turned on
   This is a touch of gamification. Think popcap/blizzard - Peggle!

** Store/visualize streaks/stats
   Implement and persist Habit.fails variable
   Seinfeld calendar view: visualize each habit streak
** Make habit descriptions editable in edit mode
   Show both editable and non editable field, show/hide as usual
** Backend sync
   Use Cloud Save or Google Drive SDK, or something else?
** Special use case on first run: guided "wizard"/overlays for adding habit to make and break
** Support Nexus 7/tablet form factors
   Add custom layout?
   Make text of each habit clickable, act as detail view trigger
   In remaining screen real-estate: show Seinfeld cal & stats for each habit?
** Add drag-n-drop reordering of each habit list
   https://github.com/bauerca/drag-sort-listview
* Dev environment
** Go through vogella and google testing material again
** Add some roboelectric tests
** Add some robotium tests + test on appthwack
** Tweak basic Junit testruns to run quicker
** Rewrite unit tests to use groovy
   Spock?
